# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "pptx/enum/base"

module Pptx
  module Enum
    # Specifies the type of a mouse action (click or hover action).
    class PP_ACTION_TYPE < Base
      # Slide show ends.
      member :END_SHOW, 6
      # Returns to the first slide.
      member :FIRST_SLIDE, 3
      # Hyperlink.
      member :HYPERLINK, 7
      # Moves to the last slide.
      member :LAST_SLIDE, 4
      # Moves to the last slide viewed.
      member :LAST_SLIDE_VIEWED, 5
      # Moves to slide specified by slide number.
      member :NAMED_SLIDE, 101
      # Runs the slideshow.
      member :NAMED_SLIDE_SHOW, 10
      # Moves to the next slide.
      member :NEXT_SLIDE, 1
      # No action is performed.
      member :NONE, 0
      # Opens the specified file.
      member :OPEN_FILE, 102
      # OLE Verb.
      member :OLE_VERB, 11
      # Begins the slideshow.
      member :PLAY, 12
      # Moves to the previous slide.
      member :PREVIOUS_SLIDE, 2
      # Runs a macro.
      member :RUN_MACRO, 8
      # Runs a program.
      member :RUN_PROGRAM, 9
    end

    # Alias of PP_ACTION_TYPE, matching the MS API name.
    PP_ACTION = PP_ACTION_TYPE
  end
end
