# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "pptx/enum/base"

module Pptx
  module Enum
    # Specifies the point on an axis where the other axis crosses.
    class XL_AXIS_CROSSES < XmlBase
      # The axis crossing point is set automatically, often at zero.
      member :AUTOMATIC, -4105, xml: "autoZero"
      # The .crosses_at property specifies the axis crossing point.
      member :CUSTOM, -4114
      # The axis crosses at the maximum value.
      member :MAXIMUM, 2, xml: "max"
      # The axis crosses at the minimum value.
      member :MINIMUM, 4, xml: "min"
    end

    # Specifies the type of the category axis.
    class XL_CATEGORY_TYPE < Base
      # The application controls the axis type.
      member :AUTOMATIC_SCALE, -4105
      # Axis groups data by an arbitrary set of categories
      member :CATEGORY_SCALE, 2
      # Axis groups data on a time scale of days, months, or years.
      member :TIME_SCALE, 3
    end

    # Specifies the type of a chart.
    class XL_CHART_TYPE < Base
      # 3D Area.
      member :THREE_D_AREA, -4098
      # 3D Stacked Area.
      member :THREE_D_AREA_STACKED, 78
      # 100% Stacked Area.
      member :THREE_D_AREA_STACKED_100, 79
      # 3D Clustered Bar.
      member :THREE_D_BAR_CLUSTERED, 60
      # 3D Stacked Bar.
      member :THREE_D_BAR_STACKED, 61
      # 3D 100% Stacked Bar.
      member :THREE_D_BAR_STACKED_100, 62
      # 3D Column.
      member :THREE_D_COLUMN, -4100
      # 3D Clustered Column.
      member :THREE_D_COLUMN_CLUSTERED, 54
      # 3D Stacked Column.
      member :THREE_D_COLUMN_STACKED, 55
      # 3D 100% Stacked Column.
      member :THREE_D_COLUMN_STACKED_100, 56
      # 3D Line.
      member :THREE_D_LINE, -4101
      # 3D Pie.
      member :THREE_D_PIE, -4102
      # Exploded 3D Pie.
      member :THREE_D_PIE_EXPLODED, 70
      # Area
      member :AREA, 1
      # Stacked Area.
      member :AREA_STACKED, 76
      # 100% Stacked Area.
      member :AREA_STACKED_100, 77
      # Clustered Bar.
      member :BAR_CLUSTERED, 57
      # Bar of Pie.
      member :BAR_OF_PIE, 71
      # Stacked Bar.
      member :BAR_STACKED, 58
      # 100% Stacked Bar.
      member :BAR_STACKED_100, 59
      # Bubble.
      member :BUBBLE, 15
      # Bubble with 3D effects.
      member :BUBBLE_THREE_D_EFFECT, 87
      # Clustered Column.
      member :COLUMN_CLUSTERED, 51
      # Stacked Column.
      member :COLUMN_STACKED, 52
      # 100% Stacked Column.
      member :COLUMN_STACKED_100, 53
      # Clustered Cone Bar.
      member :CONE_BAR_CLUSTERED, 102
      # Stacked Cone Bar.
      member :CONE_BAR_STACKED, 103
      # 100% Stacked Cone Bar.
      member :CONE_BAR_STACKED_100, 104
      # 3D Cone Column.
      member :CONE_COL, 105
      # Clustered Cone Column.
      member :CONE_COL_CLUSTERED, 99
      # Stacked Cone Column.
      member :CONE_COL_STACKED, 100
      # 100% Stacked Cone Column.
      member :CONE_COL_STACKED_100, 101
      # Clustered Cylinder Bar.
      member :CYLINDER_BAR_CLUSTERED, 95
      # Stacked Cylinder Bar.
      member :CYLINDER_BAR_STACKED, 96
      # 100% Stacked Cylinder Bar.
      member :CYLINDER_BAR_STACKED_100, 97
      # 3D Cylinder Column.
      member :CYLINDER_COL, 98
      # Clustered Cone Column.
      member :CYLINDER_COL_CLUSTERED, 92
      # Stacked Cone Column.
      member :CYLINDER_COL_STACKED, 93
      # 100% Stacked Cylinder Column.
      member :CYLINDER_COL_STACKED_100, 94
      # Doughnut.
      member :DOUGHNUT, -4120
      # Exploded Doughnut.
      member :DOUGHNUT_EXPLODED, 80
      # Line.
      member :LINE, 4
      # Line with Markers.
      member :LINE_MARKERS, 65
      # Stacked Line with Markers.
      member :LINE_MARKERS_STACKED, 66
      # 100% Stacked Line with Markers.
      member :LINE_MARKERS_STACKED_100, 67
      # Stacked Line.
      member :LINE_STACKED, 63
      # 100% Stacked Line.
      member :LINE_STACKED_100, 64
      # Pie.
      member :PIE, 5
      # Exploded Pie.
      member :PIE_EXPLODED, 69
      # Pie of Pie.
      member :PIE_OF_PIE, 68
      # Clustered Pyramid Bar.
      member :PYRAMID_BAR_CLUSTERED, 109
      # Stacked Pyramid Bar.
      member :PYRAMID_BAR_STACKED, 110
      # 100% Stacked Pyramid Bar.
      member :PYRAMID_BAR_STACKED_100, 111
      # 3D Pyramid Column.
      member :PYRAMID_COL, 112
      # Clustered Pyramid Column.
      member :PYRAMID_COL_CLUSTERED, 106
      # Stacked Pyramid Column.
      member :PYRAMID_COL_STACKED, 107
      # 100% Stacked Pyramid Column.
      member :PYRAMID_COL_STACKED_100, 108
      # Radar.
      member :RADAR, -4151
      # Filled Radar.
      member :RADAR_FILLED, 82
      # Radar with Data Markers.
      member :RADAR_MARKERS, 81
      # High-Low-Close.
      member :STOCK_HLC, 88
      # Open-High-Low-Close.
      member :STOCK_OHLC, 89
      # Volume-High-Low-Close.
      member :STOCK_VHLC, 90
      # Volume-Open-High-Low-Close.
      member :STOCK_VOHLC, 91
      # 3D Surface.
      member :SURFACE, 83
      # Surface (Top View).
      member :SURFACE_TOP_VIEW, 85
      # Surface (Top View wireframe).
      member :SURFACE_TOP_VIEW_WIREFRAME, 86
      # 3D Surface (wireframe).
      member :SURFACE_WIREFRAME, 84
      # Scatter.
      member :XY_SCATTER, -4169
      # Scatter with Lines.
      member :XY_SCATTER_LINES, 74
      # Scatter with Lines and No Data Markers.
      member :XY_SCATTER_LINES_NO_MARKERS, 75
      # Scatter with Smoothed Lines.
      member :XY_SCATTER_SMOOTH, 72
      # Scatter with Smoothed Lines and No Data Markers.
      member :XY_SCATTER_SMOOTH_NO_MARKERS, 73
    end

    # Specifies where the data label is positioned.
    class XL_DATA_LABEL_POSITION < XmlBase
      # The data label is positioned above the data point.
      member :ABOVE, 0, xml: "t"
      # The data label is positioned below the data point.
      member :BELOW, 1, xml: "b"
      # Word sets the position of the data label.
      member :BEST_FIT, 5, xml: "bestFit"
      # The data label is centered on the data point or inside a bar or a pie
      # slice.
      member :CENTER, -4108, xml: "ctr"
      # The data label is positioned inside the data point at the bottom edge.
      member :INSIDE_BASE, 4, xml: "inBase"
      # The data label is positioned inside the data point at the top edge.
      member :INSIDE_END, 3, xml: "inEnd"
      # The data label is positioned to the left of the data point.
      member :LEFT, -4131, xml: "l"
      # Data labels are in multiple positions (read-only).
      member :MIXED, 6
      # The data label is positioned outside the data point at the top edge.
      member :OUTSIDE_END, 2, xml: "outEnd"
      # The data label is positioned to the right of the data point.
      member :RIGHT, -4152, xml: "r"
    end

    # Alias of XL_DATA_LABEL_POSITION, matching the MS API name.
    XL_LABEL_POSITION = XL_DATA_LABEL_POSITION

    # Specifies the position of the legend on a chart.
    class XL_LEGEND_POSITION < XmlBase
      # Below the chart.
      member :BOTTOM, -4107, xml: "b"
      # In the upper-right corner of the chart border.
      member :CORNER, 2, xml: "tr"
      # A custom position (read-only).
      member :CUSTOM, -4161
      # Left of the chart.
      member :LEFT, -4131, xml: "l"
      # Right of the chart.
      member :RIGHT, -4152, xml: "r"
      # Above the chart.
      member :TOP, -4160, xml: "t"
    end

    # Specifies the marker style for a point or series in a line, scatter, or
    # radar chart.
    class XL_MARKER_STYLE < XmlBase
      # Automatic markers
      member :AUTOMATIC, -4105, xml: "auto"
      # Circular markers
      member :CIRCLE, 8, xml: "circle"
      # Long bar markers
      member :DASH, -4115, xml: "dash"
      # Diamond-shaped markers
      member :DIAMOND, 2, xml: "diamond"
      # Short bar markers
      member :DOT, -4118, xml: "dot"
      # No markers
      member :NONE, -4142, xml: "none"
      # Picture markers
      member :PICTURE, -4147, xml: "picture"
      # Square markers with a plus sign
      member :PLUS, 9, xml: "plus"
      # Square markers
      member :SQUARE, 1, xml: "square"
      # Square markers with an asterisk
      member :STAR, 5, xml: "star"
      # Triangular markers
      member :TRIANGLE, 3, xml: "triangle"
      # Square markers with an X
      member :X, -4168, xml: "x"
    end

    # Specifies a type of axis tick for a chart.
    class XL_TICK_MARK < XmlBase
      # Tick mark crosses the axis
      member :CROSS, 4, xml: "cross"
      # Tick mark appears inside the axis
      member :INSIDE, 2, xml: "in"
      # No tick mark
      member :NONE, -4142, xml: "none"
      # Tick mark appears outside the axis
      member :OUTSIDE, 3, xml: "out"
    end

    # Specifies the position of tick-mark labels on a chart axis.
    class XL_TICK_LABEL_POSITION < XmlBase
      # Top or right side of the chart.
      member :HIGH, -4127, xml: "high"
      # Bottom or left side of the chart.
      member :LOW, -4134, xml: "low"
      # Next to axis (where axis is not at either side of the chart).
      member :NEXT_TO_AXIS, 4, xml: "nextTo"
      # No tick labels.
      member :NONE, -4142, xml: "none"
    end
  end
end
