# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "pptx/enum/base"

module Pptx
  module Enum
    # Specifies the language identifier.
    class MSO_LANGUAGE_ID < XmlBase
      # No language specified.
      member :NONE, 0
      # The Afrikaans language.
      member :AFRIKAANS, 1078, xml: "af-ZA"
      # The Albanian language.
      member :ALBANIAN, 1052, xml: "sq-AL"
      # The Amharic language.
      member :AMHARIC, 1118, xml: "am-ET"
      # The Arabic language.
      member :ARABIC, 1025, xml: "ar-SA"
      # The Arabic Algeria language.
      member :ARABIC_ALGERIA, 5121, xml: "ar-DZ"
      # The Arabic Bahrain language.
      member :ARABIC_BAHRAIN, 15361, xml: "ar-BH"
      # The Arabic Egypt language.
      member :ARABIC_EGYPT, 3073, xml: "ar-EG"
      # The Arabic Iraq language.
      member :ARABIC_IRAQ, 2049, xml: "ar-IQ"
      # The Arabic Jordan language.
      member :ARABIC_JORDAN, 11265, xml: "ar-JO"
      # The Arabic Kuwait language.
      member :ARABIC_KUWAIT, 13313, xml: "ar-KW"
      # The Arabic Lebanon language.
      member :ARABIC_LEBANON, 12289, xml: "ar-LB"
      # The Arabic Libya language.
      member :ARABIC_LIBYA, 4097, xml: "ar-LY"
      # The Arabic Morocco language.
      member :ARABIC_MOROCCO, 6145, xml: "ar-MA"
      # The Arabic Oman language.
      member :ARABIC_OMAN, 8193, xml: "ar-OM"
      # The Arabic Qatar language.
      member :ARABIC_QATAR, 16385, xml: "ar-QA"
      # The Arabic Syria language.
      member :ARABIC_SYRIA, 10241, xml: "ar-SY"
      # The Arabic Tunisia language.
      member :ARABIC_TUNISIA, 7169, xml: "ar-TN"
      # The Arabic UAE language.
      member :ARABIC_UAE, 14337, xml: "ar-AE"
      # The Arabic Yemen language.
      member :ARABIC_YEMEN, 9217, xml: "ar-YE"
      # The Armenian language.
      member :ARMENIAN, 1067, xml: "hy-AM"
      # The Assamese language.
      member :ASSAMESE, 1101, xml: "as-IN"
      # The Azeri Cyrillic language.
      member :AZERI_CYRILLIC, 2092, xml: "az-AZ"
      # The Azeri Latin language.
      member :AZERI_LATIN, 1068, xml: "az-Latn-AZ"
      # The Basque language.
      member :BASQUE, 1069, xml: "eu-ES"
      # The Belgian Dutch language.
      member :BELGIAN_DUTCH, 2067, xml: "nl-BE"
      # The Belgian French language.
      member :BELGIAN_FRENCH, 2060, xml: "fr-BE"
      # The Bengali language.
      member :BENGALI, 1093, xml: "bn-IN"
      # The Bosnian language.
      member :BOSNIAN, 4122, xml: "hr-BA"
      # The Bosnian Bosnia Herzegovina Cyrillic language.
      member :BOSNIAN_BOSNIA_HERZEGOVINA_CYRILLIC, 8218, xml: "bs-BA"
      # The Bosnian Bosnia Herzegovina Latin language.
      member :BOSNIAN_BOSNIA_HERZEGOVINA_LATIN, 5146, xml: "bs-Latn-BA"
      # The Brazilian Portuguese language.
      member :BRAZILIAN_PORTUGUESE, 1046, xml: "pt-BR"
      # The Bulgarian language.
      member :BULGARIAN, 1026, xml: "bg-BG"
      # The Burmese language.
      member :BURMESE, 1109, xml: "my-MM"
      # The Byelorussian language.
      member :BYELORUSSIAN, 1059, xml: "be-BY"
      # The Catalan language.
      member :CATALAN, 1027, xml: "ca-ES"
      # The Cherokee language.
      member :CHEROKEE, 1116, xml: "chr-US"
      # The Chinese Hong Kong SAR language.
      member :CHINESE_HONG_KONG_SAR, 3076, xml: "zh-HK"
      # The Chinese Macao SAR language.
      member :CHINESE_MACAO_SAR, 5124, xml: "zh-MO"
      # The Chinese Singapore language.
      member :CHINESE_SINGAPORE, 4100, xml: "zh-SG"
      # The Croatian language.
      member :CROATIAN, 1050, xml: "hr-HR"
      # The Czech language.
      member :CZECH, 1029, xml: "cs-CZ"
      # The Danish language.
      member :DANISH, 1030, xml: "da-DK"
      # The Divehi language.
      member :DIVEHI, 1125, xml: "div-MV"
      # The Dutch language.
      member :DUTCH, 1043, xml: "nl-NL"
      # The Edo language.
      member :EDO, 1126, xml: "bin-NG"
      # The English AUS language.
      member :ENGLISH_AUS, 3081, xml: "en-AU"
      # The English Belize language.
      member :ENGLISH_BELIZE, 10249, xml: "en-BZ"
      # The English Canadian language.
      member :ENGLISH_CANADIAN, 4105, xml: "en-CA"
      # The English Caribbean language.
      member :ENGLISH_CARIBBEAN, 9225, xml: "en-CB"
      # The English Indonesia language.
      member :ENGLISH_INDONESIA, 14345, xml: "en-ID"
      # The English Ireland language.
      member :ENGLISH_IRELAND, 6153, xml: "en-IE"
      # The English Jamaica language.
      member :ENGLISH_JAMAICA, 8201, xml: "en-JA"
      # The English NewZealand language.
      member :ENGLISH_NEW_ZEALAND, 5129, xml: "en-NZ"
      # The English Philippines language.
      member :ENGLISH_PHILIPPINES, 13321, xml: "en-PH"
      # The English South Africa language.
      member :ENGLISH_SOUTH_AFRICA, 7177, xml: "en-ZA"
      # The English Trinidad Tobago language.
      member :ENGLISH_TRINIDAD_TOBAGO, 11273, xml: "en-TT"
      # The English UK language.
      member :ENGLISH_UK, 2057, xml: "en-GB"
      # The English US language.
      member :ENGLISH_US, 1033, xml: "en-US"
      # The English Zimbabwe language.
      member :ENGLISH_ZIMBABWE, 12297, xml: "en-ZW"
      # The Estonian language.
      member :ESTONIAN, 1061, xml: "et-EE"
      # The Faeroese language.
      member :FAEROESE, 1080, xml: "fo-FO"
      # The Farsi language.
      member :FARSI, 1065, xml: "fa-IR"
      # The Filipino language.
      member :FILIPINO, 1124, xml: "fil-PH"
      # The Finnish language.
      member :FINNISH, 1035, xml: "fi-FI"
      # The French Congo DRC language.
      member :FRANCH_CONGO_DRC, 9228, xml: "fr-CD"
      # The French language.
      member :FRENCH, 1036, xml: "fr-FR"
      # The French Cameroon language.
      member :FRENCH_CAMEROON, 11276, xml: "fr-CM"
      # The French Canadian language.
      member :FRENCH_CANADIAN, 3084, xml: "fr-CA"
      # The French Coted Ivoire language.
      member :FRENCH_COTED_IVOIRE, 12300, xml: "fr-CI"
      # The French Haiti language.
      member :FRENCH_HAITI, 15372, xml: "fr-HT"
      # The French Luxembourg language.
      member :FRENCH_LUXEMBOURG, 5132, xml: "fr-LU"
      # The French Mali language.
      member :FRENCH_MALI, 13324, xml: "fr-ML"
      # The French Monaco language.
      member :FRENCH_MONACO, 6156, xml: "fr-MC"
      # The French Morocco language.
      member :FRENCH_MOROCCO, 14348, xml: "fr-MA"
      # The French Reunion language.
      member :FRENCH_REUNION, 8204, xml: "fr-RE"
      # The French Senegal language.
      member :FRENCH_SENEGAL, 10252, xml: "fr-SN"
      # The French West Indies language.
      member :FRENCH_WEST_INDIES, 7180, xml: "fr-WINDIES"
      # The Frisian Netherlands language.
      member :FRISIAN_NETHERLANDS, 1122, xml: "fy-NL"
      # The Fulfulde language.
      member :FULFULDE, 1127, xml: "ff-NG"
      # The Gaelic Ireland language.
      member :GAELIC_IRELAND, 2108, xml: "ga-IE"
      # The Gaelic Scotland language.
      member :GAELIC_SCOTLAND, 1084, xml: "en-US"
      # The Galician language.
      member :GALICIAN, 1110, xml: "gl-ES"
      # The Georgian language.
      member :GEORGIAN, 1079, xml: "ka-GE"
      # The German language.
      member :GERMAN, 1031, xml: "de-DE"
      # The German Austria language.
      member :GERMAN_AUSTRIA, 3079, xml: "de-AT"
      # The German Liechtenstein language.
      member :GERMAN_LIECHTENSTEIN, 5127, xml: "de-LI"
      # The German Luxembourg language.
      member :GERMAN_LUXEMBOURG, 4103, xml: "de-LU"
      # The Greek language.
      member :GREEK, 1032, xml: "el-GR"
      # The Guarani language.
      member :GUARANI, 1140, xml: "gn-PY"
      # The Gujarati language.
      member :GUJARATI, 1095, xml: "gu-IN"
      # The Hausa language.
      member :HAUSA, 1128, xml: "ha-NG"
      # The Hawaiian language.
      member :HAWAIIAN, 1141, xml: "haw-US"
      # The Hebrew language.
      member :HEBREW, 1037, xml: "he-IL"
      # The Hindi language.
      member :HINDI, 1081, xml: "hi-IN"
      # The Hungarian language.
      member :HUNGARIAN, 1038, xml: "hu-HU"
      # The Ibibio language.
      member :IBIBIO, 1129, xml: "ibb-NG"
      # The Icelandic language.
      member :ICELANDIC, 1039, xml: "is-IS"
      # The Igbo language.
      member :IGBO, 1136, xml: "ig-NG"
      # The Indonesian language.
      member :INDONESIAN, 1057, xml: "id-ID"
      # The Inuktitut language.
      member :INUKTITUT, 1117, xml: "iu-Cans-CA"
      # The Italian language.
      member :ITALIAN, 1040, xml: "it-IT"
      # The Japanese language.
      member :JAPANESE, 1041, xml: "ja-JP"
      # The Kannada language.
      member :KANNADA, 1099, xml: "kn-IN"
      # The Kanuri language.
      member :KANURI, 1137, xml: "kr-NG"
      # The Kashmiri language.
      member :KASHMIRI, 1120, xml: "ks-Arab"
      # The Kashmiri Devanagari language.
      member :KASHMIRI_DEVANAGARI, 2144, xml: "ks-Deva"
      # The Kazakh language.
      member :KAZAKH, 1087, xml: "kk-KZ"
      # The Khmer language.
      member :KHMER, 1107, xml: "kh-KH"
      # The Kirghiz language.
      member :KIRGHIZ, 1088, xml: "ky-KG"
      # The Konkani language.
      member :KONKANI, 1111, xml: "kok-IN"
      # The Korean language.
      member :KOREAN, 1042, xml: "ko-KR"
      # The Lao language.
      member :LAO, 1108, xml: "lo-LA"
      # The Latin language.
      member :LATIN, 1142, xml: "la-Latn"
      # The Latvian language.
      member :LATVIAN, 1062, xml: "lv-LV"
      # The Lithuanian language.
      member :LITHUANIAN, 1063, xml: "lt-LT"
      # The Macedonian FYROM language.
      member :MACEDONINAN_FYROM, 1071, xml: "mk-MK"
      # The Malay Brunei Darussalam language.
      member :MALAY_BRUNEI_DARUSSALAM, 2110, xml: "ms-BN"
      # The Malayalam language.
      member :MALAYALAM, 1100, xml: "ml-IN"
      # The Malaysian language.
      member :MALAYSIAN, 1086, xml: "ms-MY"
      # The Maltese language.
      member :MALTESE, 1082, xml: "mt-MT"
      # The Manipuri language.
      member :MANIPURI, 1112, xml: "mni-IN"
      # The Maori language.
      member :MAORI, 1153, xml: "mi-NZ"
      # The Marathi language.
      member :MARATHI, 1102, xml: "mr-IN"
      # The Mexican Spanish language.
      member :MEXICAN_SPANISH, 2058, xml: "es-MX"
      # The Mongolian language.
      member :MONGOLIAN, 1104, xml: "mn-MN"
      # The Nepali language.
      member :NEPALI, 1121, xml: "ne-NP"
      # No proofing.
      member :NO_PROOFING, 1024, xml: "en-US"
      # The Norwegian Bokmol language.
      member :NORWEGIAN_BOKMOL, 1044, xml: "nb-NO"
      # The Norwegian Nynorsk language.
      member :NORWEGIAN_NYNORSK, 2068, xml: "nn-NO"
      # The Oriya language.
      member :ORIYA, 1096, xml: "or-IN"
      # The Oromo language.
      member :OROMO, 1138, xml: "om-Ethi-ET"
      # The Pashto language.
      member :PASHTO, 1123, xml: "ps-AF"
      # The Polish language.
      member :POLISH, 1045, xml: "pl-PL"
      # The Portuguese language.
      member :PORTUGUESE, 2070, xml: "pt-PT"
      # The Punjabi language.
      member :PUNJABI, 1094, xml: "pa-IN"
      # The Quechua Bolivia language.
      member :QUECHUA_BOLIVIA, 1131, xml: "quz-BO"
      # The Quechua Ecuador language.
      member :QUECHUA_ECUADOR, 2155, xml: "quz-EC"
      # The Quechua Peru language.
      member :QUECHUA_PERU, 3179, xml: "quz-PE"
      # The Rhaeto Romanic language.
      member :RHAETO_ROMANIC, 1047, xml: "rm-CH"
      # The Romanian language.
      member :ROMANIAN, 1048, xml: "ro-RO"
      # The Romanian Moldova language.
      member :ROMANIAN_MOLDOVA, 2072, xml: "ro-MO"
      # The Russian language.
      member :RUSSIAN, 1049, xml: "ru-RU"
      # The Russian Moldova language.
      member :RUSSIAN_MOLDOVA, 2073, xml: "ru-MO"
      # The Sami Lappish language.
      member :SAMI_LAPPISH, 1083, xml: "se-NO"
      # The Sanskrit language.
      member :SANSKRIT, 1103, xml: "sa-IN"
      # The Sepedi language.
      member :SEPEDI, 1132, xml: "ns-ZA"
      # The Serbian Bosnia Herzegovina Cyrillic language.
      member :SERBIAN_BOSNIA_HERZEGOVINA_CYRILLIC, 7194, xml: "sr-BA"
      # The Serbian Bosnia Herzegovina Latin language.
      member :SERBIAN_BOSNIA_HERZEGOVINA_LATIN, 6170, xml: "sr-Latn-BA"
      # The Serbian Cyrillic language.
      member :SERBIAN_CYRILLIC, 3098, xml: "sr-SP"
      # The Serbian Latin language.
      member :SERBIAN_LATIN, 2074, xml: "sr-Latn-CS"
      # The Sesotho language.
      member :SESOTHO, 1072, xml: "st-ZA"
      # The Simplified Chinese language.
      member :SIMPLIFIED_CHINESE, 2052, xml: "zh-CN"
      # The Sindhi language.
      member :SINDHI, 1113, xml: "sd-Deva-IN"
      # The Sindhi Pakistan language.
      member :SINDHI_PAKISTAN, 2137, xml: "sd-Arab-PK"
      # The Sinhalese language.
      member :SINHALESE, 1115, xml: "si-LK"
      # The Slovak language.
      member :SLOVAK, 1051, xml: "sk-SK"
      # The Slovenian language.
      member :SLOVENIAN, 1060, xml: "sl-SI"
      # The Somali language.
      member :SOMALI, 1143, xml: "so-SO"
      # The Sorbian language.
      member :SORBIAN, 1070, xml: "wen-DE"
      # The Spanish language.
      member :SPANISH, 1034, xml: "es-ES_tradnl"
      # The Spanish Argentina language.
      member :SPANISH_ARGENTINA, 11274, xml: "es-AR"
      # The Spanish Bolivia language.
      member :SPANISH_BOLIVIA, 16394, xml: "es-BO"
      # The Spanish Chile language.
      member :SPANISH_CHILE, 13322, xml: "es-CL"
      # The Spanish Colombia language.
      member :SPANISH_COLOMBIA, 9226, xml: "es-CO"
      # The Spanish Costa Rica language.
      member :SPANISH_COSTA_RICA, 5130, xml: "es-CR"
      # The Spanish Dominican Republic language.
      member :SPANISH_DOMINICAN_REPUBLIC, 7178, xml: "es-DO"
      # The Spanish Ecuador language.
      member :SPANISH_ECUADOR, 12298, xml: "es-EC"
      # The Spanish El Salvador language.
      member :SPANISH_EL_SALVADOR, 17418, xml: "es-SV"
      # The Spanish Guatemala language.
      member :SPANISH_GUATEMALA, 4106, xml: "es-GT"
      # The Spanish Honduras language.
      member :SPANISH_HONDURAS, 18442, xml: "es-HN"
      # The Spanish Modern Sort language.
      member :SPANISH_MODERN_SORT, 3082, xml: "es-ES"
      # The Spanish Nicaragua language.
      member :SPANISH_NICARAGUA, 19466, xml: "es-NI"
      # The Spanish Panama language.
      member :SPANISH_PANAMA, 6154, xml: "es-PA"
      # The Spanish Paraguay language.
      member :SPANISH_PARAGUAY, 15370, xml: "es-PY"
      # The Spanish Peru language.
      member :SPANISH_PERU, 10250, xml: "es-PE"
      # The Spanish Puerto Rico language.
      member :SPANISH_PUERTO_RICO, 20490, xml: "es-PR"
      # The Spanish Uruguay language.
      member :SPANISH_URUGUAY, 14346, xml: "es-UR"
      # The Spanish Venezuela language.
      member :SPANISH_VENEZUELA, 8202, xml: "es-VE"
      # The Swahili language.
      member :SWAHILI, 1089, xml: "sw-KE"
      # The Swedish language.
      member :SWEDISH, 1053, xml: "sv-SE"
      # The Swedish Finland language.
      member :SWEDISH_FINLAND, 2077, xml: "sv-FI"
      # The Swiss French language.
      member :SWISS_FRENCH, 4108, xml: "fr-CH"
      # The Swiss German language.
      member :SWISS_GERMAN, 2055, xml: "de-CH"
      # The Swiss Italian language.
      member :SWISS_ITALIAN, 2064, xml: "it-CH"
      # The Syriac language.
      member :SYRIAC, 1114, xml: "syr-SY"
      # The Tajik language.
      member :TAJIK, 1064, xml: "tg-TJ"
      # The Tamazight language.
      member :TAMAZIGHT, 1119, xml: "tzm-Arab-MA"
      # The Tamazight Latin language.
      member :TAMAZIGHT_LATIN, 2143, xml: "tmz-DZ"
      # The Tamil language.
      member :TAMIL, 1097, xml: "ta-IN"
      # The Tatar language.
      member :TATAR, 1092, xml: "tt-RU"
      # The Telugu language.
      member :TELUGU, 1098, xml: "te-IN"
      # The Thai language.
      member :THAI, 1054, xml: "th-TH"
      # The Tibetan language.
      member :TIBETAN, 1105, xml: "bo-CN"
      # The Tigrigna Eritrea language.
      member :TIGRIGNA_ERITREA, 2163, xml: "ti-ER"
      # The Tigrigna Ethiopic language.
      member :TIGRIGNA_ETHIOPIC, 1139, xml: "ti-ET"
      # The Traditional Chinese language.
      member :TRADITIONAL_CHINESE, 1028, xml: "zh-TW"
      # The Tsonga language.
      member :TSONGA, 1073, xml: "ts-ZA"
      # The Tswana language.
      member :TSWANA, 1074, xml: "tn-ZA"
      # The Turkish language.
      member :TURKISH, 1055, xml: "tr-TR"
      # The Turkmen language.
      member :TURKMEN, 1090, xml: "tk-TM"
      # The Ukrainian language.
      member :UKRAINIAN, 1058, xml: "uk-UA"
      # The Urdu language.
      member :URDU, 1056, xml: "ur-PK"
      # The Uzbek Cyrillic language.
      member :UZBEK_CYRILLIC, 2115, xml: "uz-UZ"
      # The Uzbek Latin language.
      member :UZBEK_LATIN, 1091, xml: "uz-Latn-UZ"
      # The Venda language.
      member :VENDA, 1075, xml: "ve-ZA"
      # The Vietnamese language.
      member :VIETNAMESE, 1066, xml: "vi-VN"
      # The Welsh language.
      member :WELSH, 1106, xml: "cy-GB"
      # The Xhosa language.
      member :XHOSA, 1076, xml: "xh-ZA"
      # The Yi language.
      member :YI, 1144, xml: "ii-CN"
      # The Yiddish language.
      member :YIDDISH, 1085, xml: "yi-Hebr"
      # The Yoruba language.
      member :YORUBA, 1130, xml: "yo-NG"
      # The Zulu language.
      member :ZULU, 1077, xml: "zu-ZA"
      # More than one language in specified range (read-only).
      member :MIXED, -2
    end
  end
end
