# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "pptx/enum/base"

module Pptx
  module Enum
    # Determines the type of automatic sizing allowed.
    class MSO_AUTO_SIZE < Base
      # No automatic sizing of the shape or text will be done.
      member :NONE, 0
      # The shape height and possibly width are adjusted to fit the text.
      member :SHAPE_TO_FIT_TEXT, 1
      # The font size is reduced as necessary to fit the text within the
      # shape.
      member :TEXT_TO_FIT_SHAPE, 2
      # Return value only; indicates a combination of automatic sizing schemes
      # are used.
      member :MIXED, -2
    end

    # Indicates the type of underline for text. Used with
    # :attr:`.Font.underline` to specify the style of text underlining.
    class MSO_TEXT_UNDERLINE_TYPE < XmlBase
      # Specifies no underline.
      member :NONE, 0, xml: "none"
      # Specifies a dash underline.
      member :DASH_HEAVY_LINE, 8, xml: "dashHeavy"
      # Specifies a dash line underline.
      member :DASH_LINE, 7, xml: "dash"
      # Specifies a long heavy line underline.
      member :DASH_LONG_HEAVY_LINE, 10, xml: "dashLongHeavy"
      # Specifies a dashed long line underline.
      member :DASH_LONG_LINE, 9, xml: "dashLong"
      # Specifies a dot dash heavy line underline.
      member :DOT_DASH_HEAVY_LINE, 12, xml: "dotDashHeavy"
      # Specifies a dot dash line underline.
      member :DOT_DASH_LINE, 11, xml: "dotDash"
      # Specifies a dot dot dash heavy line underline.
      member :DOT_DOT_DASH_HEAVY_LINE, 14, xml: "dotDotDashHeavy"
      # Specifies a dot dot dash line underline.
      member :DOT_DOT_DASH_LINE, 13, xml: "dotDotDash"
      # Specifies a dotted heavy line underline.
      member :DOTTED_HEAVY_LINE, 6, xml: "dottedHeavy"
      # Specifies a dotted line underline.
      member :DOTTED_LINE, 5, xml: "dotted"
      # Specifies a double line underline.
      member :DOUBLE_LINE, 3, xml: "dbl"
      # Specifies a heavy line underline.
      member :HEAVY_LINE, 4, xml: "heavy"
      # Specifies a single line underline.
      member :SINGLE_LINE, 2, xml: "sng"
      # Specifies a wavy double line underline.
      member :WAVY_DOUBLE_LINE, 17, xml: "wavyDbl"
      # Specifies a wavy heavy line underline.
      member :WAVY_HEAVY_LINE, 16, xml: "wavyHeavy"
      # Specifies a wavy line underline.
      member :WAVY_LINE, 15, xml: "wavy"
      # Specifies underlining words.
      member :WORDS, 1, xml: "words"
      # Specifies a mix of underline types (read-only).
      member :MIXED, -2
    end

    # Alias of MSO_TEXT_UNDERLINE_TYPE, matching the MS API name.
    MSO_UNDERLINE = MSO_TEXT_UNDERLINE_TYPE

    # Specifies the vertical alignment of text in a text frame.
    class MSO_VERTICAL_ANCHOR < XmlBase
      # Aligns text to top of text frame
      member :TOP, 1, xml: "t"
      # Centers text vertically
      member :MIDDLE, 3, xml: "ctr"
      # Aligns text to bottom of text frame
      member :BOTTOM, 4, xml: "b"
      # Return value only; indicates a combination of the other states.
      member :MIXED, -2
    end

    # Alias of MSO_VERTICAL_ANCHOR, matching the MS API name.
    MSO_ANCHOR = MSO_VERTICAL_ANCHOR

    # Specifies the horizontal alignment for one or more paragraphs.
    class PP_PARAGRAPH_ALIGNMENT < XmlBase
      # Center align
      member :CENTER, 2, xml: "ctr"
      # Evenly distributes e.g. Japanese characters from left to right within
      # a line
      member :DISTRIBUTE, 5, xml: "dist"
      # Justified, i.e. each line both begins and ends at the margin.
      member :JUSTIFY, 4, xml: "just"
      # Justify using a small amount of space between words.
      member :JUSTIFY_LOW, 7, xml: "justLow"
      # Left aligned
      member :LEFT, 1, xml: "l"
      # Right aligned
      member :RIGHT, 3, xml: "r"
      # Thai distributed
      member :THAI_DISTRIBUTE, 6, xml: "thaiDist"
      # Multiple alignments are present in a set of paragraphs (read-only).
      member :MIXED, -2
    end

    # Alias of PP_PARAGRAPH_ALIGNMENT, matching the MS API name.
    PP_ALIGN = PP_PARAGRAPH_ALIGNMENT
  end
end
