# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "ruby_pptx/enum/base"

module Pptx
  module Enum
    # Specifies the color specification scheme
    class MSO_COLOR_TYPE < Base
      # Color is specified by an |RGBColor| value.
      member :RGB, 1
      # Color is one of the preset theme colors
      member :SCHEME, 2
      # Color is specified using Hue, Saturation, and Luminosity values
      member :HSL, 101
      # Color is specified using a named built-in color
      member :PRESET, 102
      # Color is an scRGB color, a wide color gamut RGB color space
      member :SCRGB, 103
      # Color is one specified by the operating system, such as the window
      # background color.
      member :SYSTEM, 104
    end

    # Specifies the type of bitmap used for the fill of a shape.
    class MSO_FILL_TYPE < Base
      # The shape is transparent, such that whatever is behind the shape shows
      # through. Often this is the slide background, but if a visible shape is
      # behind, that will show through.
      member :BACKGROUND, 5
      # Shape is filled with a gradient
      member :GRADIENT, 3
      # Shape is part of a group and should inherit the fill properties of the
      # group.
      member :GROUP, 101
      # Shape is filled with a pattern
      member :PATTERNED, 2
      # Shape is filled with a bitmapped image
      member :PICTURE, 6
      # Shape is filled with a solid color
      member :SOLID, 1
      # Shape is filled with a texture
      member :TEXTURED, 4
    end

    # Alias of MSO_FILL_TYPE, matching the MS API name.
    MSO_FILL = MSO_FILL_TYPE

    # Specifies the dash style for a line.
    class MSO_LINE_DASH_STYLE < XmlBase
      # Line consists of dashes only.
      member :DASH, 4, xml: "dash"
      # Line is a dash-dot pattern.
      member :DASH_DOT, 5, xml: "dashDot"
      # Line is a dash-dot-dot pattern.
      member :DASH_DOT_DOT, 6, xml: "lgDashDotDot"
      # Line consists of long dashes.
      member :LONG_DASH, 7, xml: "lgDash"
      # Line is a long dash-dot pattern.
      member :LONG_DASH_DOT, 8, xml: "lgDashDot"
      # Line is made up of round dots.
      member :ROUND_DOT, 3, xml: "sysDot"
      # Line is solid.
      member :SOLID, 1, xml: "solid"
      # Line is made up of square dots.
      member :SQUARE_DOT, 2, xml: "sysDash"
      # Not supported.
      member :DASH_STYLE_MIXED, -2
    end

    # Alias of MSO_LINE_DASH_STYLE, matching the MS API name.
    MSO_LINE = MSO_LINE_DASH_STYLE

    # Specifies the fill pattern used in a shape.
    class MSO_PATTERN_TYPE < XmlBase
      # Cross
      member :CROSS, 51, xml: "cross"
      # Dark Downward Diagonal
      member :DARK_DOWNWARD_DIAGONAL, 15, xml: "dkDnDiag"
      # Dark Horizontal
      member :DARK_HORIZONTAL, 13, xml: "dkHorz"
      # Dark Upward Diagonal
      member :DARK_UPWARD_DIAGONAL, 16, xml: "dkUpDiag"
      # Dark Vertical
      member :DARK_VERTICAL, 14, xml: "dkVert"
      # Dashed Downward Diagonal
      member :DASHED_DOWNWARD_DIAGONAL, 28, xml: "dashDnDiag"
      # Dashed Horizontal
      member :DASHED_HORIZONTAL, 32, xml: "dashHorz"
      # Dashed Upward Diagonal
      member :DASHED_UPWARD_DIAGONAL, 27, xml: "dashUpDiag"
      # Dashed Vertical
      member :DASHED_VERTICAL, 31, xml: "dashVert"
      # Diagonal Brick
      member :DIAGONAL_BRICK, 40, xml: "diagBrick"
      # Diagonal Cross
      member :DIAGONAL_CROSS, 54, xml: "diagCross"
      # Pattern Divot
      member :DIVOT, 46, xml: "divot"
      # Dotted Diamond
      member :DOTTED_DIAMOND, 24, xml: "dotDmnd"
      # Dotted Grid
      member :DOTTED_GRID, 45, xml: "dotGrid"
      # Downward Diagonal
      member :DOWNWARD_DIAGONAL, 52, xml: "dnDiag"
      # Horizontal
      member :HORIZONTAL, 49, xml: "horz"
      # Horizontal Brick
      member :HORIZONTAL_BRICK, 35, xml: "horzBrick"
      # Large Checker Board
      member :LARGE_CHECKER_BOARD, 36, xml: "lgCheck"
      # Large Confetti
      member :LARGE_CONFETTI, 33, xml: "lgConfetti"
      # Large Grid
      member :LARGE_GRID, 34, xml: "lgGrid"
      # Light Downward Diagonal
      member :LIGHT_DOWNWARD_DIAGONAL, 21, xml: "ltDnDiag"
      # Light Horizontal
      member :LIGHT_HORIZONTAL, 19, xml: "ltHorz"
      # Light Upward Diagonal
      member :LIGHT_UPWARD_DIAGONAL, 22, xml: "ltUpDiag"
      # Light Vertical
      member :LIGHT_VERTICAL, 20, xml: "ltVert"
      # Narrow Horizontal
      member :NARROW_HORIZONTAL, 30, xml: "narHorz"
      # Narrow Vertical
      member :NARROW_VERTICAL, 29, xml: "narVert"
      # Outlined Diamond
      member :OUTLINED_DIAMOND, 41, xml: "openDmnd"
      # 10% of the foreground color.
      member :PERCENT_10, 2, xml: "pct10"
      # 20% of the foreground color.
      member :PERCENT_20, 3, xml: "pct20"
      # 25% of the foreground color.
      member :PERCENT_25, 4, xml: "pct25"
      # 30% of the foreground color.
      member :PERCENT_30, 5, xml: "pct30"
      # 40% of the foreground color.
      member :ERCENT_40, 6, xml: "pct40"
      # 5% of the foreground color.
      member :PERCENT_5, 1, xml: "pct5"
      # 50% of the foreground color.
      member :PERCENT_50, 7, xml: "pct50"
      # 60% of the foreground color.
      member :PERCENT_60, 8, xml: "pct60"
      # 70% of the foreground color.
      member :PERCENT_70, 9, xml: "pct70"
      # 75% of the foreground color.
      member :PERCENT_75, 10, xml: "pct75"
      # 80% of the foreground color.
      member :PERCENT_80, 11, xml: "pct80"
      # 90% of the foreground color.
      member :PERCENT_90, 12, xml: "pct90"
      # Plaid
      member :PLAID, 42, xml: "plaid"
      # Shingle
      member :SHINGLE, 47, xml: "shingle"
      # Small Checker Board
      member :SMALL_CHECKER_BOARD, 17, xml: "smCheck"
      # Small Confetti
      member :SMALL_CONFETTI, 37, xml: "smConfetti"
      # Small Grid
      member :SMALL_GRID, 23, xml: "smGrid"
      # Solid Diamond
      member :SOLID_DIAMOND, 39, xml: "solidDmnd"
      # Sphere
      member :SPHERE, 43, xml: "sphere"
      # Trellis
      member :TRELLIS, 18, xml: "trellis"
      # Upward Diagonal
      member :UPWARD_DIAGONAL, 53, xml: "upDiag"
      # Vertical
      member :VERTICAL, 50, xml: "vert"
      # Wave
      member :WAVE, 48, xml: "wave"
      # Weave
      member :WEAVE, 44, xml: "weave"
      # Wide Downward Diagonal
      member :WIDE_DOWNWARD_DIAGONAL, 25, xml: "wdDnDiag"
      # Wide Upward Diagonal
      member :WIDE_UPWARD_DIAGONAL, 26, xml: "wdUpDiag"
      # Zig Zag
      member :ZIG_ZAG, 38, xml: "zigZag"
      # Mixed pattern (read-only).
      member :MIXED, -2
    end

    # Alias of MSO_PATTERN_TYPE, matching the MS API name.
    MSO_PATTERN = MSO_PATTERN_TYPE

    # An Office theme color, one of those shown in the color gallery on the
    # formatting ribbon.
    class MSO_THEME_COLOR_INDEX < XmlBase
      # Indicates the color is not a theme color.
      member :NOT_THEME_COLOR, 0
      # Specifies the Accent 1 theme color.
      member :ACCENT_1, 5, xml: "accent1"
      # Specifies the Accent 2 theme color.
      member :ACCENT_2, 6, xml: "accent2"
      # Specifies the Accent 3 theme color.
      member :ACCENT_3, 7, xml: "accent3"
      # Specifies the Accent 4 theme color.
      member :ACCENT_4, 8, xml: "accent4"
      # Specifies the Accent 5 theme color.
      member :ACCENT_5, 9, xml: "accent5"
      # Specifies the Accent 6 theme color.
      member :ACCENT_6, 10, xml: "accent6"
      # Specifies the Background 1 theme color.
      member :BACKGROUND_1, 14, xml: "bg1"
      # Specifies the Background 2 theme color.
      member :BACKGROUND_2, 16, xml: "bg2"
      # Specifies the Dark 1 theme color.
      member :DARK_1, 1, xml: "dk1"
      # Specifies the Dark 2 theme color.
      member :DARK_2, 3, xml: "dk2"
      # Specifies the theme color for a clicked hyperlink.
      member :FOLLOWED_HYPERLINK, 12, xml: "folHlink"
      # Specifies the theme color for a hyperlink.
      member :HYPERLINK, 11, xml: "hlink"
      # Specifies the Light 1 theme color.
      member :LIGHT_1, 2, xml: "lt1"
      # Specifies the Light 2 theme color.
      member :LIGHT_2, 4, xml: "lt2"
      # Specifies the Text 1 theme color.
      member :TEXT_1, 13, xml: "tx1"
      # Specifies the Text 2 theme color.
      member :TEXT_2, 15, xml: "tx2"
      # Indicates multiple theme colors are used, such as in a group shape
      # (read-only).
      member :MIXED, -2
    end

    # Alias of MSO_THEME_COLOR_INDEX, matching the MS API name.
    MSO_THEME_COLOR = MSO_THEME_COLOR_INDEX
  end
end
