# frozen_string_literal: true

# Generated by tools/generate_enums.py from python-pptx 1.0.2. Do not edit by hand.

require "ruby_pptx/enum/base"

module Pptx
  module Enum
    # Specifies a type of AutoShape, e.g. DOWN_ARROW.
    class MSO_AUTO_SHAPE_TYPE < XmlBase
      # Back or Previous button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_BACK_OR_PREVIOUS, 129, xml: "actionButtonBackPrevious"
      # Beginning button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_BEGINNING, 131, xml: "actionButtonBeginning"
      # Button with no default picture or text. Supports mouse-click and
      # mouse-over actions
      member :ACTION_BUTTON_CUSTOM, 125, xml: "actionButtonBlank"
      # Document button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_DOCUMENT, 134, xml: "actionButtonDocument"
      # End button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_END, 132, xml: "actionButtonEnd"
      # Forward or Next button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_FORWARD_OR_NEXT, 130, xml: "actionButtonForwardNext"
      # Help button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_HELP, 127, xml: "actionButtonHelp"
      # Home button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_HOME, 126, xml: "actionButtonHome"
      # Information button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_INFORMATION, 128, xml: "actionButtonInformation"
      # Movie button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_MOVIE, 136, xml: "actionButtonMovie"
      # Return button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_RETURN, 133, xml: "actionButtonReturn"
      # Sound button. Supports mouse-click and mouse-over actions
      member :ACTION_BUTTON_SOUND, 135, xml: "actionButtonSound"
      # Arc
      member :ARC, 25, xml: "arc"
      # Rounded Rectangular Callout
      member :BALLOON, 137, xml: "wedgeRoundRectCallout"
      # Block arrow that follows a curved 90-degree angle
      member :BENT_ARROW, 41, xml: "bentArrow"
      # Block arrow that follows a sharp 90-degree angle. Points up by default
      member :BENT_UP_ARROW, 44, xml: "bentUpArrow"
      # Bevel
      member :BEVEL, 15, xml: "bevel"
      # Block arc
      member :BLOCK_ARC, 20, xml: "blockArc"
      # Can
      member :CAN, 13, xml: "can"
      # Chart Plus
      member :CHART_PLUS, 182, xml: "chartPlus"
      # Chart Star
      member :CHART_STAR, 181, xml: "chartStar"
      # Chart X
      member :CHART_X, 180, xml: "chartX"
      # Chevron
      member :CHEVRON, 52, xml: "chevron"
      # Geometric chord shape
      member :CHORD, 161, xml: "chord"
      # Block arrow that follows a curved 180-degree angle
      member :CIRCULAR_ARROW, 60, xml: "circularArrow"
      # Cloud
      member :CLOUD, 179, xml: "cloud"
      # Cloud callout
      member :CLOUD_CALLOUT, 108, xml: "cloudCallout"
      # Corner
      member :CORNER, 162, xml: "corner"
      # Corner Tabs
      member :CORNER_TABS, 169, xml: "cornerTabs"
      # Cross
      member :CROSS, 11, xml: "plus"
      # Cube
      member :CUBE, 14, xml: "cube"
      # Block arrow that curves down
      member :CURVED_DOWN_ARROW, 48, xml: "curvedDownArrow"
      # Ribbon banner that curves down
      member :CURVED_DOWN_RIBBON, 100, xml: "ellipseRibbon"
      # Block arrow that curves left
      member :CURVED_LEFT_ARROW, 46, xml: "curvedLeftArrow"
      # Block arrow that curves right
      member :CURVED_RIGHT_ARROW, 45, xml: "curvedRightArrow"
      # Block arrow that curves up
      member :CURVED_UP_ARROW, 47, xml: "curvedUpArrow"
      # Ribbon banner that curves up
      member :CURVED_UP_RIBBON, 99, xml: "ellipseRibbon2"
      # Decagon
      member :DECAGON, 144, xml: "decagon"
      # Diagonal Stripe
      member :DIAGONAL_STRIPE, 141, xml: "diagStripe"
      # Diamond
      member :DIAMOND, 4, xml: "diamond"
      # Dodecagon
      member :DODECAGON, 146, xml: "dodecagon"
      # Donut
      member :DONUT, 18, xml: "donut"
      # Double brace
      member :DOUBLE_BRACE, 27, xml: "bracePair"
      # Double bracket
      member :DOUBLE_BRACKET, 26, xml: "bracketPair"
      # Double wave
      member :DOUBLE_WAVE, 104, xml: "doubleWave"
      # Block arrow that points down
      member :DOWN_ARROW, 36, xml: "downArrow"
      # Callout with arrow that points down
      member :DOWN_ARROW_CALLOUT, 56, xml: "downArrowCallout"
      # Ribbon banner with center area below ribbon ends
      member :DOWN_RIBBON, 98, xml: "ribbon"
      # Explosion
      member :EXPLOSION1, 89, xml: "irregularSeal1"
      # Explosion
      member :EXPLOSION2, 90, xml: "irregularSeal2"
      # Alternate process flowchart symbol
      member :FLOWCHART_ALTERNATE_PROCESS, 62, xml: "flowChartAlternateProcess"
      # Card flowchart symbol
      member :FLOWCHART_CARD, 75, xml: "flowChartPunchedCard"
      # Collate flowchart symbol
      member :FLOWCHART_COLLATE, 79, xml: "flowChartCollate"
      # Connector flowchart symbol
      member :FLOWCHART_CONNECTOR, 73, xml: "flowChartConnector"
      # Data flowchart symbol
      member :FLOWCHART_DATA, 64, xml: "flowChartInputOutput"
      # Decision flowchart symbol
      member :FLOWCHART_DECISION, 63, xml: "flowChartDecision"
      # Delay flowchart symbol
      member :FLOWCHART_DELAY, 84, xml: "flowChartDelay"
      # Direct access storage flowchart symbol
      member :FLOWCHART_DIRECT_ACCESS_STORAGE, 87, xml: "flowChartMagneticDrum"
      # Display flowchart symbol
      member :FLOWCHART_DISPLAY, 88, xml: "flowChartDisplay"
      # Document flowchart symbol
      member :FLOWCHART_DOCUMENT, 67, xml: "flowChartDocument"
      # Extract flowchart symbol
      member :FLOWCHART_EXTRACT, 81, xml: "flowChartExtract"
      # Internal storage flowchart symbol
      member :FLOWCHART_INTERNAL_STORAGE, 66, xml: "flowChartInternalStorage"
      # Magnetic disk flowchart symbol
      member :FLOWCHART_MAGNETIC_DISK, 86, xml: "flowChartMagneticDisk"
      # Manual input flowchart symbol
      member :FLOWCHART_MANUAL_INPUT, 71, xml: "flowChartManualInput"
      # Manual operation flowchart symbol
      member :FLOWCHART_MANUAL_OPERATION, 72, xml: "flowChartManualOperation"
      # Merge flowchart symbol
      member :FLOWCHART_MERGE, 82, xml: "flowChartMerge"
      # Multi-document flowchart symbol
      member :FLOWCHART_MULTIDOCUMENT, 68, xml: "flowChartMultidocument"
      # Offline Storage
      member :FLOWCHART_OFFLINE_STORAGE, 139, xml: "flowChartOfflineStorage"
      # Off-page connector flowchart symbol
      member :FLOWCHART_OFFPAGE_CONNECTOR, 74, xml: "flowChartOffpageConnector"
      # "Or" flowchart symbol
      member :FLOWCHART_OR, 78, xml: "flowChartOr"
      # Predefined process flowchart symbol
      member :FLOWCHART_PREDEFINED_PROCESS, 65, xml: "flowChartPredefinedProcess"
      # Preparation flowchart symbol
      member :FLOWCHART_PREPARATION, 70, xml: "flowChartPreparation"
      # Process flowchart symbol
      member :FLOWCHART_PROCESS, 61, xml: "flowChartProcess"
      # Punched tape flowchart symbol
      member :FLOWCHART_PUNCHED_TAPE, 76, xml: "flowChartPunchedTape"
      # Sequential access storage flowchart symbol
      member :FLOWCHART_SEQUENTIAL_ACCESS_STORAGE, 85, xml: "flowChartMagneticTape"
      # Sort flowchart symbol
      member :FLOWCHART_SORT, 80, xml: "flowChartSort"
      # Stored data flowchart symbol
      member :FLOWCHART_STORED_DATA, 83, xml: "flowChartOnlineStorage"
      # Summing junction flowchart symbol
      member :FLOWCHART_SUMMING_JUNCTION, 77, xml: "flowChartSummingJunction"
      # Terminator flowchart symbol
      member :FLOWCHART_TERMINATOR, 69, xml: "flowChartTerminator"
      # Folded corner
      member :FOLDED_CORNER, 16, xml: "foldedCorner"
      # Frame
      member :FRAME, 158, xml: "frame"
      # Funnel
      member :FUNNEL, 174, xml: "funnel"
      # Gear 6
      member :GEAR_6, 172, xml: "gear6"
      # Gear 9
      member :GEAR_9, 173, xml: "gear9"
      # Half Frame
      member :HALF_FRAME, 159, xml: "halfFrame"
      # Heart
      member :HEART, 21, xml: "heart"
      # Heptagon
      member :HEPTAGON, 145, xml: "heptagon"
      # Hexagon
      member :HEXAGON, 10, xml: "hexagon"
      # Horizontal scroll
      member :HORIZONTAL_SCROLL, 102, xml: "horizontalScroll"
      # Isosceles triangle
      member :ISOSCELES_TRIANGLE, 7, xml: "triangle"
      # Block arrow that points left
      member :LEFT_ARROW, 34, xml: "leftArrow"
      # Callout with arrow that points left
      member :LEFT_ARROW_CALLOUT, 54, xml: "leftArrowCallout"
      # Left brace
      member :LEFT_BRACE, 31, xml: "leftBrace"
      # Left bracket
      member :LEFT_BRACKET, 29, xml: "leftBracket"
      # Left Circular Arrow
      member :LEFT_CIRCULAR_ARROW, 176, xml: "leftCircularArrow"
      # Block arrow with arrowheads that point both left and right
      member :LEFT_RIGHT_ARROW, 37, xml: "leftRightArrow"
      # Callout with arrowheads that point both left and right
      member :LEFT_RIGHT_ARROW_CALLOUT, 57, xml: "leftRightArrowCallout"
      # Left Right Circular Arrow
      member :LEFT_RIGHT_CIRCULAR_ARROW, 177, xml: "leftRightCircularArrow"
      # Left Right Ribbon
      member :LEFT_RIGHT_RIBBON, 140, xml: "leftRightRibbon"
      # Block arrow with arrowheads that point left, right, and up
      member :LEFT_RIGHT_UP_ARROW, 40, xml: "leftRightUpArrow"
      # Block arrow with arrowheads that point left and up
      member :LEFT_UP_ARROW, 43, xml: "leftUpArrow"
      # Lightning bolt
      member :LIGHTNING_BOLT, 22, xml: "lightningBolt"
      # Callout with border and horizontal callout line
      member :LINE_CALLOUT_1, 109, xml: "borderCallout1"
      # Callout with vertical accent bar
      member :LINE_CALLOUT_1_ACCENT_BAR, 113, xml: "accentCallout1"
      # Callout with border and vertical accent bar
      member :LINE_CALLOUT_1_BORDER_AND_ACCENT_BAR, 121, xml: "accentBorderCallout1"
      # Callout with horizontal line
      member :LINE_CALLOUT_1_NO_BORDER, 117, xml: "callout1"
      # Callout with diagonal straight line
      member :LINE_CALLOUT_2, 110, xml: "borderCallout2"
      # Callout with diagonal callout line and accent bar
      member :LINE_CALLOUT_2_ACCENT_BAR, 114, xml: "accentCallout2"
      # Callout with border, diagonal straight line, and accent bar
      member :LINE_CALLOUT_2_BORDER_AND_ACCENT_BAR, 122, xml: "accentBorderCallout2"
      # Callout with no border and diagonal callout line
      member :LINE_CALLOUT_2_NO_BORDER, 118, xml: "callout2"
      # Callout with angled line
      member :LINE_CALLOUT_3, 111, xml: "borderCallout3"
      # Callout with angled callout line and accent bar
      member :LINE_CALLOUT_3_ACCENT_BAR, 115, xml: "accentCallout3"
      # Callout with border, angled callout line, and accent bar
      member :LINE_CALLOUT_3_BORDER_AND_ACCENT_BAR, 123, xml: "accentBorderCallout3"
      # Callout with no border and angled callout line
      member :LINE_CALLOUT_3_NO_BORDER, 119, xml: "callout3"
      # Callout with callout line segments forming a U-shape.
      member :LINE_CALLOUT_4, 112, xml: "borderCallout3"
      # Callout with accent bar and callout line segments forming a U-shape.
      member :LINE_CALLOUT_4_ACCENT_BAR, 116, xml: "accentCallout3"
      # Callout with border, accent bar, and callout line segments forming a
      # U-shape.
      member :LINE_CALLOUT_4_BORDER_AND_ACCENT_BAR, 124, xml: "accentBorderCallout3"
      # Callout with no border and callout line segments forming a U-shape.
      member :LINE_CALLOUT_4_NO_BORDER, 120, xml: "callout3"
      # Straight Connector
      member :LINE_INVERSE, 183, xml: "lineInv"
      # Division
      member :MATH_DIVIDE, 166, xml: "mathDivide"
      # Equal
      member :MATH_EQUAL, 167, xml: "mathEqual"
      # Minus
      member :MATH_MINUS, 164, xml: "mathMinus"
      # Multiply
      member :MATH_MULTIPLY, 165, xml: "mathMultiply"
      # Not Equal
      member :MATH_NOT_EQUAL, 168, xml: "mathNotEqual"
      # Plus
      member :MATH_PLUS, 163, xml: "mathPlus"
      # Moon
      member :MOON, 24, xml: "moon"
      # Non-isosceles Trapezoid
      member :NON_ISOSCELES_TRAPEZOID, 143, xml: "nonIsoscelesTrapezoid"
      # Notched block arrow that points right
      member :NOTCHED_RIGHT_ARROW, 50, xml: "notchedRightArrow"
      # 'No' Symbol
      member :NO_SYMBOL, 19, xml: "noSmoking"
      # Octagon
      member :OCTAGON, 6, xml: "octagon"
      # Oval
      member :OVAL, 9, xml: "ellipse"
      # Oval-shaped callout
      member :OVAL_CALLOUT, 107, xml: "wedgeEllipseCallout"
      # Parallelogram
      member :PARALLELOGRAM, 2, xml: "parallelogram"
      # Pentagon
      member :PENTAGON, 51, xml: "homePlate"
      # Pie
      member :PIE, 142, xml: "pie"
      # Pie
      member :PIE_WEDGE, 175, xml: "pieWedge"
      # Plaque
      member :PLAQUE, 28, xml: "plaque"
      # Plaque Tabs
      member :PLAQUE_TABS, 171, xml: "plaqueTabs"
      # Block arrows that point up, down, left, and right
      member :QUAD_ARROW, 39, xml: "quadArrow"
      # Callout with arrows that point up, down, left, and right
      member :QUAD_ARROW_CALLOUT, 59, xml: "quadArrowCallout"
      # Rectangle
      member :RECTANGLE, 1, xml: "rect"
      # Rectangular callout
      member :RECTANGULAR_CALLOUT, 105, xml: "wedgeRectCallout"
      # Pentagon
      member :REGULAR_PENTAGON, 12, xml: "pentagon"
      # Block arrow that points right
      member :RIGHT_ARROW, 33, xml: "rightArrow"
      # Callout with arrow that points right
      member :RIGHT_ARROW_CALLOUT, 53, xml: "rightArrowCallout"
      # Right brace
      member :RIGHT_BRACE, 32, xml: "rightBrace"
      # Right bracket
      member :RIGHT_BRACKET, 30, xml: "rightBracket"
      # Right triangle
      member :RIGHT_TRIANGLE, 8, xml: "rtTriangle"
      # Rounded rectangle
      member :ROUNDED_RECTANGLE, 5, xml: "roundRect"
      # Rounded rectangle-shaped callout
      member :ROUNDED_RECTANGULAR_CALLOUT, 106, xml: "wedgeRoundRectCallout"
      # Round Single Corner Rectangle
      member :ROUND_1_RECTANGLE, 151, xml: "round1Rect"
      # Round Diagonal Corner Rectangle
      member :ROUND_2_DIAG_RECTANGLE, 153, xml: "round2DiagRect"
      # Round Same Side Corner Rectangle
      member :ROUND_2_SAME_RECTANGLE, 152, xml: "round2SameRect"
      # Smiley face
      member :SMILEY_FACE, 17, xml: "smileyFace"
      # Snip Single Corner Rectangle
      member :SNIP_1_RECTANGLE, 155, xml: "snip1Rect"
      # Snip Diagonal Corner Rectangle
      member :SNIP_2_DIAG_RECTANGLE, 157, xml: "snip2DiagRect"
      # Snip Same Side Corner Rectangle
      member :SNIP_2_SAME_RECTANGLE, 156, xml: "snip2SameRect"
      # Snip and Round Single Corner Rectangle
      member :SNIP_ROUND_RECTANGLE, 154, xml: "snipRoundRect"
      # Square Tabs
      member :SQUARE_TABS, 170, xml: "squareTabs"
      # 10-Point Star
      member :STAR_10_POINT, 149, xml: "star10"
      # 12-Point Star
      member :STAR_12_POINT, 150, xml: "star12"
      # 16-point star
      member :STAR_16_POINT, 94, xml: "star16"
      # 24-point star
      member :STAR_24_POINT, 95, xml: "star24"
      # 32-point star
      member :STAR_32_POINT, 96, xml: "star32"
      # 4-point star
      member :STAR_4_POINT, 91, xml: "star4"
      # 5-point star
      member :STAR_5_POINT, 92, xml: "star5"
      # 6-Point Star
      member :STAR_6_POINT, 147, xml: "star6"
      # 7-Point Star
      member :STAR_7_POINT, 148, xml: "star7"
      # 8-point star
      member :STAR_8_POINT, 93, xml: "star8"
      # Block arrow that points right with stripes at the tail
      member :STRIPED_RIGHT_ARROW, 49, xml: "stripedRightArrow"
      # Sun
      member :SUN, 23, xml: "sun"
      # Swoosh Arrow
      member :SWOOSH_ARROW, 178, xml: "swooshArrow"
      # Teardrop
      member :TEAR, 160, xml: "teardrop"
      # Trapezoid
      member :TRAPEZOID, 3, xml: "trapezoid"
      # Block arrow that points up
      member :UP_ARROW, 35, xml: "upArrow"
      # Callout with arrow that points up
      member :UP_ARROW_CALLOUT, 55, xml: "upArrowCallout"
      # Block arrow that points up and down
      member :UP_DOWN_ARROW, 38, xml: "upDownArrow"
      # Callout with arrows that point up and down
      member :UP_DOWN_ARROW_CALLOUT, 58, xml: "upDownArrowCallout"
      # Ribbon banner with center area above ribbon ends
      member :UP_RIBBON, 97, xml: "ribbon2"
      # Block arrow forming a U shape
      member :U_TURN_ARROW, 42, xml: "uturnArrow"
      # Vertical scroll
      member :VERTICAL_SCROLL, 101, xml: "verticalScroll"
      # Wave
      member :WAVE, 103, xml: "wave"
    end

    # Alias of MSO_AUTO_SHAPE_TYPE, matching the MS API name.
    MSO_SHAPE = MSO_AUTO_SHAPE_TYPE

    # Specifies a type of connector.
    class MSO_CONNECTOR_TYPE < XmlBase
      # Curved connector.
      member :CURVE, 3, xml: "curvedConnector3"
      # Elbow connector.
      member :ELBOW, 2, xml: "bentConnector3"
      # Straight line connector.
      member :STRAIGHT, 1, xml: "line"
      # Return value only; indicates a combination of other states.
      member :MIXED, -2
    end

    # Alias of MSO_CONNECTOR_TYPE, matching the MS API name.
    MSO_CONNECTOR = MSO_CONNECTOR_TYPE

    # Specifies the type of a shape, more specifically than the five base types.
    class MSO_SHAPE_TYPE < Base
      # AutoShape
      member :AUTO_SHAPE, 1
      # Callout shape
      member :CALLOUT, 2
      # Drawing canvas
      member :CANVAS, 20
      # Chart, e.g. pie chart, bar chart
      member :CHART, 3
      # Comment
      member :COMMENT, 4
      # Diagram
      member :DIAGRAM, 21
      # Embedded OLE object
      member :EMBEDDED_OLE_OBJECT, 7
      # Form control
      member :FORM_CONTROL, 8
      # Freeform
      member :FREEFORM, 5
      # Group shape
      member :GROUP, 6
      # SmartArt graphic
      member :IGX_GRAPHIC, 24
      # Ink
      member :INK, 22
      # Ink Comment
      member :INK_COMMENT, 23
      # Line
      member :LINE, 9
      # Linked OLE object
      member :LINKED_OLE_OBJECT, 10
      # Linked picture
      member :LINKED_PICTURE, 11
      # Media
      member :MEDIA, 16
      # OLE control object
      member :OLE_CONTROL_OBJECT, 12
      # Picture
      member :PICTURE, 13
      # Placeholder
      member :PLACEHOLDER, 14
      # Script anchor
      member :SCRIPT_ANCHOR, 18
      # Table
      member :TABLE, 19
      # Text box
      member :TEXT_BOX, 17
      # Text effect
      member :TEXT_EFFECT, 15
      # Web video
      member :WEB_VIDEO, 26
      # Multiple shape types (read-only).
      member :MIXED, -2
    end

    # Alias of MSO_SHAPE_TYPE, matching the MS API name.
    MSO = MSO_SHAPE_TYPE

    # Indicates the OLE media type.
    class PP_MEDIA_TYPE < Base
      # Video media such as MP4.
      member :MOVIE, 3
      # Other media types
      member :OTHER, 1
      # Return value only; indicates multiple media types, typically for a
      # collection of shapes. May not be applicable in python-pptx.
      member :MIXED, -2
    end

    # Specifies one of the 18 distinct types of placeholder.
    class PP_PLACEHOLDER_TYPE < XmlBase
      # Clip art placeholder
      member :BITMAP, 9, xml: "clipArt"
      # Body
      member :BODY, 2, xml: "body"
      # Center Title
      member :CENTER_TITLE, 3, xml: "ctrTitle"
      # Chart
      member :CHART, 8, xml: "chart"
      # Date
      member :DATE, 16, xml: "dt"
      # Footer
      member :FOOTER, 15, xml: "ftr"
      # Header
      member :HEADER, 14, xml: "hdr"
      # Media Clip
      member :MEDIA_CLIP, 10, xml: "media"
      # Object
      member :OBJECT, 7, xml: "obj"
      # SmartArt placeholder. Organization chart is a legacy name.
      member :ORG_CHART, 11, xml: "dgm"
      # Picture
      member :PICTURE, 18, xml: "pic"
      # Slide Image
      member :SLIDE_IMAGE, 101, xml: "sldImg"
      # Slide Number
      member :SLIDE_NUMBER, 13, xml: "sldNum"
      # Subtitle
      member :SUBTITLE, 4, xml: "subTitle"
      # Table
      member :TABLE, 12, xml: "tbl"
      # Title
      member :TITLE, 1, xml: "title"
      # Vertical Body (read-only).
      member :VERTICAL_BODY, 6
      # Vertical Object (read-only).
      member :VERTICAL_OBJECT, 17
      # Vertical Title (read-only).
      member :VERTICAL_TITLE, 5
      # Return value only; multiple placeholders of differing types.
      member :MIXED, -2
    end

    # Alias of PP_PLACEHOLDER_TYPE, matching the MS API name.
    PP_PLACEHOLDER = PP_PLACEHOLDER_TYPE
  end
end
