# frozen_string_literal: true

require "nokogiri"
require "zip"

require "pptx/version"
require "pptx/errors"
require "pptx/length"
require "pptx/geometry"
require "pptx/oxml/ns"
require "pptx/oxml/simple_types"
require "pptx/oxml/element"
require "pptx/oxml/content_model"
require "pptx/opc/pack_uri"
require "pptx/opc/constants"
require "pptx/opc/spec"
require "pptx/opc/oxml"
require "pptx/opc/serialized"
require "pptx/opc/package"

require "pptx/sliceable"
require "pptx/pattern_matching"
require "pptx/element_proxy"
require "pptx/oxml/presentation"
require "pptx/oxml/slide"
require "pptx/oxml/core_properties"
require "pptx/oxml/dml/color"
require "pptx/oxml/dml/fill"
require "pptx/oxml/text"
require "pptx/dml/color"
require "pptx/dml/fill"
require "pptx/oxml/theme"
require "pptx/theme"
require "pptx/text/text"
require "pptx/text/font_metrics"
require "pptx/text/fitter"
require "pptx/oxml/table"
require "pptx/oxml/chart"
require "pptx/chart/data"
require "pptx/chart/workbook_writer"
require "pptx/chart/xy_data"
require "pptx/chart/xml_writer"
require "pptx/chart/format"
require "pptx/chart/combo"
require "pptx/chart/chart"
require "pptx/image"
require "pptx/media"
require "pptx/oxml/action"
require "pptx/action"
require "pptx/oxml/shapes/shared"
require "pptx/oxml/shapes/autoshape"
require "pptx/oxml/shapes/groupshape"
require "pptx/oxml/shapes/other"
require "pptx/autoshape_spec"
require "pptx/shapes/base"
require "pptx/shapes/shape"
require "pptx/shapes/placeholder"
require "pptx/shapes/freeform"
require "pptx/shapes/authoring"
require "pptx/shapes/shape_tree"
require "pptx/oxml/section"
require "pptx/slide"
require "pptx/section"
require "pptx/table_paging"
require "pptx/builder"
require "pptx/presentation"
require "pptx/parts/core_properties"
require "pptx/parts/image"
require "pptx/parts/media"
require "pptx/parts/chart"
require "pptx/parts/slide"
require "pptx/parts/presentation"
require "pptx/parts/theme"
require "pptx/package"

require "pptx/enum/base"
require "pptx/enum/action"
require "pptx/enum/chart"
require "pptx/enum/dml"
require "pptx/enum/lang"
require "pptx/enum/shapes"
require "pptx/enum/text"

# A Ruby object model for PowerPoint (.pptx) files, ported from python-pptx.
module Pptx
end
