# frozen_string_literal: true

require "nokogiri"
require "zip"

require "pptx/version"
require "pptx/errors"
require "pptx/length"
require "pptx/oxml/ns"
require "pptx/oxml/simple_types"
require "pptx/oxml/element"
require "pptx/oxml/content_model"
require "pptx/opc/pack_uri"
require "pptx/opc/constants"
require "pptx/opc/spec"
require "pptx/opc/oxml"
require "pptx/opc/serialized"
require "pptx/opc/package"

require "pptx/element_proxy"
require "pptx/oxml/presentation"
require "pptx/oxml/slide"
require "pptx/oxml/core_properties"
require "pptx/oxml/dml/color"
require "pptx/oxml/dml/fill"
require "pptx/oxml/text"
require "pptx/dml/color"
require "pptx/dml/fill"
require "pptx/text/text"
require "pptx/oxml/table"
require "pptx/image"
require "pptx/oxml/shapes/shared"
require "pptx/oxml/shapes/autoshape"
require "pptx/oxml/shapes/groupshape"
require "pptx/oxml/shapes/other"
require "pptx/autoshape_spec"
require "pptx/shapes/base"
require "pptx/shapes/shape"
require "pptx/shapes/placeholder"
require "pptx/shapes/shape_tree"
require "pptx/slide"
require "pptx/presentation"
require "pptx/parts/core_properties"
require "pptx/parts/image"
require "pptx/parts/slide"
require "pptx/parts/presentation"
require "pptx/package"

require "pptx/enum/base"
require "pptx/enum/action"
require "pptx/enum/chart"
require "pptx/enum/dml"
require "pptx/enum/lang"
require "pptx/enum/shapes"
require "pptx/enum/text"

# A Ruby object model for PowerPoint (.pptx) files, ported from python-pptx.
module Pptx
end
