# frozen_string_literal: true

# Nokogiri is not required here: Pptx::Oxml::Backend loads it when it can
# and falls back to REXML when it cannot, as under ruby.wasm.
require "zip"

require "ruby_pptx/version"
require "ruby_pptx/errors"
require "ruby_pptx/length"
require "ruby_pptx/geometry"
require "ruby_pptx/oxml/ns"
require "ruby_pptx/oxml/simple_types"
require "ruby_pptx/oxml/element"
require "ruby_pptx/oxml/content_model"
require "ruby_pptx/opc/pack_uri"
require "ruby_pptx/opc/constants"
require "ruby_pptx/opc/spec"
require "ruby_pptx/opc/oxml"
require "ruby_pptx/opc/serialized"
require "ruby_pptx/opc/package"

require "ruby_pptx/sliceable"
require "ruby_pptx/pattern_matching"
require "ruby_pptx/element_proxy"
require "ruby_pptx/oxml/presentation"
require "ruby_pptx/oxml/slide"
require "ruby_pptx/oxml/core_properties"
require "ruby_pptx/oxml/dml/color"
require "ruby_pptx/oxml/dml/fill"
require "ruby_pptx/oxml/text"
require "ruby_pptx/dml/color"
require "ruby_pptx/dml/fill"
require "ruby_pptx/dml/effect"
require "ruby_pptx/oxml/theme"
require "ruby_pptx/theme"
require "ruby_pptx/text/text"
require "ruby_pptx/text/font_metrics"
require "ruby_pptx/text/fitter"
require "ruby_pptx/oxml/table"
require "ruby_pptx/oxml/chart"
require "ruby_pptx/chart/data"
require "ruby_pptx/chart/workbook_writer"
require "ruby_pptx/chart/xy_data"
require "ruby_pptx/chart/xml_writer"
require "ruby_pptx/chart/format"
require "ruby_pptx/chart/combo"
require "ruby_pptx/chart/chart"
require "ruby_pptx/image"
require "ruby_pptx/media"
require "ruby_pptx/oxml/action"
require "ruby_pptx/action"
require "ruby_pptx/oxml/shapes/shared"
require "ruby_pptx/oxml/shapes/autoshape"
require "ruby_pptx/oxml/shapes/groupshape"
require "ruby_pptx/oxml/shapes/other"
require "ruby_pptx/autoshape_spec"
require "ruby_pptx/shapes/base"
require "ruby_pptx/shapes/shape"
require "ruby_pptx/shapes/placeholder"
require "ruby_pptx/shapes/freeform"
require "ruby_pptx/shapes/adjustments"
require "ruby_pptx/shapes/authoring"
require "ruby_pptx/shapes/shape_tree"
require "ruby_pptx/oxml/section"
require "ruby_pptx/slide"
require "ruby_pptx/section"
require "ruby_pptx/table_paging"
require "ruby_pptx/builder"
require "ruby_pptx/presentation"
require "ruby_pptx/parts/core_properties"
require "ruby_pptx/parts/image"
require "ruby_pptx/parts/media"
require "ruby_pptx/parts/chart"
require "ruby_pptx/parts/slide"
require "ruby_pptx/parts/presentation"
require "ruby_pptx/parts/theme"
require "ruby_pptx/parts/embedded_package"
require "ruby_pptx/package"

require "ruby_pptx/enum/base"
require "ruby_pptx/enum/action"
require "ruby_pptx/enum/chart"
require "ruby_pptx/enum/dml"
require "ruby_pptx/enum/lang"
require "ruby_pptx/enum/shapes"
require "ruby_pptx/enum/text"
require "ruby_pptx/enum/prog_id"

# A Ruby object model for PowerPoint (.pptx) files, ported from python-pptx.
module Pptx
  # The XML library in use: :nokogiri, or :rexml where Nokogiri cannot be
  # loaded (ruby.wasm) or RUBY_PPTX_XML_BACKEND=rexml asks for it. Output is
  # the same either way; Nokogiri is several times faster.
  def self.xml_backend
    Oxml::BACKEND.name
  end
end
