# frozen_string_literal: true

# Generated by tools/generate_opc_constants.py from python-pptx. Do not edit by hand.

require "pptx/opc/constants"

module Pptx
  module Opc
    # (extension, content-type) pairs that may be expressed as a
    # <Default> element in [Content_Types].xml rather than an <Override>.
    DEFAULT_CONTENT_TYPES = [
      ["bin", CONTENT_TYPE::PML_PRINTER_SETTINGS],
      ["bin", CONTENT_TYPE::SML_PRINTER_SETTINGS],
      ["bin", CONTENT_TYPE::WML_PRINTER_SETTINGS],
      ["bmp", CONTENT_TYPE::BMP],
      ["emf", CONTENT_TYPE::X_EMF],
      ["fntdata", CONTENT_TYPE::X_FONTDATA],
      ["gif", CONTENT_TYPE::GIF],
      ["jpe", CONTENT_TYPE::JPEG],
      ["jpeg", CONTENT_TYPE::JPEG],
      ["jpg", CONTENT_TYPE::JPEG],
      ["mov", CONTENT_TYPE::MOV],
      ["mp4", CONTENT_TYPE::MP4],
      ["mpg", CONTENT_TYPE::MPG],
      ["png", CONTENT_TYPE::PNG],
      ["rels", CONTENT_TYPE::OPC_RELATIONSHIPS],
      ["tif", CONTENT_TYPE::TIFF],
      ["tiff", CONTENT_TYPE::TIFF],
      ["vid", CONTENT_TYPE::VIDEO],
      ["wdp", CONTENT_TYPE::MS_PHOTO],
      ["wmf", CONTENT_TYPE::X_WMF],
      ["wmv", CONTENT_TYPE::WMV],
      ["xlsx", CONTENT_TYPE::SML_SHEET],
      ["xml", CONTENT_TYPE::XML],
    ].freeze
  end
end
