"""Generate lib/pptx/opc/constants.rb and spec.rb from python-pptx.

These are long lists of literal MIME types and relationship URIs; introspecting
them is both faster and safer than retyping several hundred strings.
"""

from __future__ import annotations

import pathlib

from pptx.opc import constants as C
from pptx.opc.spec import default_content_types

OUT = pathlib.Path(__file__).resolve().parent.parent / "lib" / "pptx" / "opc"


def members(cls):
    return sorted(
        (name, value)
        for name, value in vars(cls).items()
        if name.isupper() and isinstance(value, str)
    )


def emit_const_class(cls, indent="    "):
    lines = [f"{indent}module {cls.__name__}"]
    for name, value in members(cls):
        lines.append(f'{indent}  {name} = "{value}"')
    lines.append(f"{indent}end")
    return "\n".join(lines)


def main() -> None:
    blocks = "\n\n".join(
        emit_const_class(cls)
        for cls in (
            C.CONTENT_TYPE,
            C.NAMESPACE,
            C.RELATIONSHIP_TARGET_MODE,
            C.RELATIONSHIP_TYPE,
        )
    )
    (OUT / "constants.rb").write_text(
        "# frozen_string_literal: true\n\n"
        "# Generated by tools/generate_opc_constants.py from python-pptx. "
        "Do not edit by hand.\n\n"
        "module Pptx\n  module Opc\n"
        f"{blocks}\n"
        "  end\nend\n"
    )

    pairs = "\n".join(
        f'      ["{ext}", CONTENT_TYPE::{_ct_name(ct)}],' for ext, ct in default_content_types
    )
    (OUT / "spec.rb").write_text(
        "# frozen_string_literal: true\n\n"
        "# Generated by tools/generate_opc_constants.py from python-pptx. "
        "Do not edit by hand.\n\n"
        'require "pptx/opc/constants"\n\n'
        "module Pptx\n"
        "  module Opc\n"
        "    # (extension, content-type) pairs that may be expressed as a\n"
        "    # <Default> element in [Content_Types].xml rather than an <Override>.\n"
        "    DEFAULT_CONTENT_TYPES = [\n"
        f"{pairs}\n"
        "    ].freeze\n"
        "  end\n"
        "end\n"
    )
    print("wrote constants.rb and spec.rb")


def _ct_name(value: str) -> str:
    for name, v in vars(C.CONTENT_TYPE).items():
        if name.isupper() and v == value:
            return name
    raise KeyError(value)


if __name__ == "__main__":
    main()
