"""Generate lib/ruby_pptx/autoshape_spec.rb from python-pptx's autoshape_types table.

182 entries of basename and default adjustment values; introspecting beats
retyping them.
"""

from __future__ import annotations

import pathlib

from pptx.spec import autoshape_types

OUT = pathlib.Path(__file__).resolve().parent.parent / "lib" / "ruby_pptx" / "autoshape_spec.rb"


def ruby_str(value: str) -> str:
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    rows = []
    for member, spec in sorted(autoshape_types.items(), key=lambda kv: kv[0].name):
        av = ", ".join(f"[{ruby_str(n)}, {v}]" for n, v in spec["avLst"])
        rows.append(
            f"      {member.name}: {{ basename: {ruby_str(spec['basename'])}, "
            f"default_adjustments: [{av}].freeze }}.freeze,"
        )
    body = "\n".join(rows)
    OUT.write_text(
        "# frozen_string_literal: true\n\n"
        "# Generated by tools/generate_autoshape_spec.py from python-pptx. "
        "Do not edit by hand.\n\n"
        'require "ruby_pptx/enum/shapes"\n\n'
        "module Pptx\n"
        "  # Per auto-shape-type metadata: the name PowerPoint gives a new shape\n"
        "  # of that type, and the default values of its adjustment handles.\n"
        "  module AutoShapeSpec\n"
        "    SPECS = {\n"
        f"{body}\n"
        "    }.freeze\n\n"
        "    module_function\n\n"
        "    # @param shape_type [Pptx::Enum::MSO_SHAPE]\n"
        "    def for(shape_type)\n"
        "      SPECS.fetch(Enum::MSO_SHAPE.fetch(shape_type).name) do\n"
        "        raise ArgumentError, \"no auto-shape spec for #{shape_type.inspect}\"\n"
        "      end\n"
        "    end\n\n"
        # No endless methods: RDoc 7 cannot parse them (see .rubocop.yml).
        "    def basename(shape_type)\n"
        "      self.for(shape_type)[:basename]\n"
        "    end\n\n"
        "    def default_adjustments(shape_type)\n"
        "      self.for(shape_type)[:default_adjustments]\n"
        "    end\n"
        "  end\n"
        "end\n"
    )
    print(f"wrote {OUT} ({len(rows)} entries)")


if __name__ == "__main__":
    main()
