"""Generate lib/pptx/enum/*.rb from python-pptx's enumerations.

Transcribing ~1100 enum members by hand would be error-prone and dull; this
introspects the real classes instead, so the Ruby constants cannot drift from
upstream. Re-run after a python-pptx upgrade and diff the result.
"""

from __future__ import annotations

import importlib
import inspect
import pathlib
import textwrap

from pptx.enum.base import BaseEnum, BaseXmlEnum

MODULES = ["action", "chart", "dml", "lang", "shapes", "text"]
OUT = pathlib.Path(__file__).resolve().parent.parent / "lib" / "pptx" / "enum"


def ruby_str(value: str) -> str:
    return '"%s"' % value.replace("\\", "\\\\").replace('"', '\\"')


def first_line(docstring: str | None) -> str:
    if not docstring:
        return ""
    text = textwrap.dedent(docstring).strip()
    # Take the leading sentence, collapsed onto one line.
    para = text.split("\n\n")[0].replace("\n", " ").strip()
    return " ".join(para.split())


def emit_enum(cls, aliases: list[str]) -> str:
    is_xml = issubclass(cls, BaseXmlEnum)
    base = "XmlBase" if is_xml else "Base"
    lines: list[str] = []

    doc = first_line(cls.__doc__)
    if doc:
        for line in textwrap.wrap(doc, width=74):
            lines.append(f"    # {line}")
    lines.append(f"    class {cls.__name__} < {base}")

    for member in cls:
        member_doc = first_line(member.__doc__)
        if member_doc:
            for line in textwrap.wrap(member_doc, width=70):
                lines.append(f"      # {line}")
        if is_xml and member.xml_value:
            lines.append(
                f"      member :{member.name}, {member.value}, xml: {ruby_str(member.xml_value)}"
            )
        else:
            lines.append(f"      member :{member.name}, {member.value}")
    lines.append("    end")

    for alias in aliases:
        lines.append("")
        lines.append(f"    # Alias of {cls.__name__}, matching the MS API name.")
        lines.append(f"    {alias} = {cls.__name__}")

    return "\n".join(lines)


def emit_module(mod_name: str) -> str:
    module = importlib.import_module("pptx.enum." + mod_name)

    canonical: dict[type, list[str]] = {}
    for name, obj in vars(module).items():
        if not (inspect.isclass(obj) and issubclass(obj, (BaseEnum, BaseXmlEnum))):
            continue
        if obj in (BaseEnum, BaseXmlEnum) or obj.__module__ != module.__name__:
            continue
        canonical.setdefault(obj, [])
        if name != obj.__name__:
            canonical[obj].append(name)

    body = "\n\n".join(emit_enum(cls, aliases) for cls, aliases in canonical.items())
    return (
        "# frozen_string_literal: true\n\n"
        "# Generated by tools/generate_enums.py from python-pptx "
        f"{importlib.import_module('pptx').__version__}. Do not edit by hand.\n\n"
        'require "pptx/enum/base"\n\n'
        "module Pptx\n"
        "  module Enum\n"
        f"{body}\n"
        "  end\n"
        "end\n"
    )


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for mod_name in MODULES:
        path = OUT / f"{mod_name}.rb"
        path.write_text(emit_module(mod_name))
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
